[project]
name = "aquiche"
version = "2.0.0"
description = "Async cache in-memory"
authors = [
    { name = "Jakub Jantosik", email = "jakub.jantosik@gmail.com" }
]
readme = "README.md"

requires-python = ">=3.9"
dependencies = [
    "typing-extensions>=4.4.0 ; python_full_version < '3.10'",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.14.1",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.2",
    "pytest-freezegun>=0.4.2",
    "pytest-mock>=3.14.0",
    "pytest-timeout>=2.3.1",
    "ruff>=0.9.2",
]

[tool.ruff]
line-length = 120

target-version = "py39"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
timeout = 30

[[tool.mypy.overrides]]
ignore_missing_imports = true
