[project]
name = "aquiche"
version = "2.0.0"
description = "Async cache in-memory"
authors = [
    { name = "Jakub Jantosik", email = "jakub.jantosik@gmail.com" }
]
readme = "README.md"

classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Internet",
]

requires-python = ">=3.10"
dependencies = [
    "typing-extensions>=4.4.0 ; python_full_version < '3.10'",
]

[build-system]
requires = ["uv_build>=0.9.1,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "mypy>=1.18.2",
    "pytest>=8.4.2",
    "pytest-asyncio>=1.2.0",
    "pytest-freezeblaster>=2.1.0",
    "pytest-mock>=3.15.1",
    "pytest-timeout>=2.4.0",
    "ruff>=0.14.0",
]

[tool.ruff]
target-version = "py10"
line-length = 120
lint.extend-select = ["I"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
timeout = 30

[tool.mypy]
ignore_missing_imports = true
